title: Мой аж супер-пупер блог
author: vaszol
email: vaszol@mail.ru
description: > # this means to ignore newlines until "baseurl:"
 Описания тут нет.. совсем.

# social links
# twitter_username: your-twitter-handle
# github_username:  your-github-handle
telegram_username: vaszol

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
